name: Learning Github Script

on:
  issues:
    types: [opened]
    
  workflow_dispatch:
  
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: " You've created this issue using GitHub Script  "
              })
              
      - name: Add issue to the project board
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              github.projects.createCard({
              column_id: 18930026,
              content_id: context.payload.issue.id,
              content_type: "Issue"
              });
      
